<!-- si besion pour commande token = $data['input'][0] -->

<div class="pageProductPublic">

    <h1><?= htmlspecialchars($data['input'][2]['categoryName']); ?></h1>

    <?php foreach ($data['input'][1] as $key => $valeur) : ?>

        <article>
            <div class="contImg">
                <img class="modal-trigger" src=' public/uploads/<?= htmlspecialchars($valeur['picture']); ?>' alt="petite photo <?= htmlspecialchars($valeur["productName"]); ?>" />
            </div>

            <div id="<?= htmlspecialchars($valeur['picture']); ?>" class="modal-window">
                <img src=' public/uploads/<?= htmlspecialchars($valeur['picture']); ?>' alt="grande photo <?= htmlspecialchars($valeur["productName"]); ?>" />
            </div>

            <div class="textProd">
                <div>
                    <h2><?= htmlspecialchars($valeur["productName"]); ?></h2>
                    <p><?= htmlspecialchars($valeur["description"]); ?></p>
                </div>
                <div>
                    <?php
                    // verification de l'existance d'items actifs 
                    if (!empty($valeur['items'])) {
                        // remplissage d'une liste déroulante avec chaque item 
                        $id = "idFormItem" . htmlspecialchars($valeur['id_product']);
                        // recupération du prix du premier item pour affichage initial
                        $firstPrice = htmlspecialchars($valeur['items'][0]['price']);
                        echo " Conditionnement :";
                        echo " <select class='selectItems' name='item' id='$id'>";
                        foreach ($valeur['items'] as $key => $item) {
                            if ($valeur['id_product'] == $item['id_product']) : ?>
                                <option value="<?= htmlspecialchars($item["id_item"]); ?>"><?= htmlspecialchars($item["pack"]); ?></option>
                    <?php endif;
                        }
                        echo "</select>";
                        $idPrix = "idPrix" . htmlspecialchars($valeur['id_product']);
                        // zone d'affichage du prix
                        echo "<div id='$idPrix'>Prix : $firstPrice Euros</div>";
                    }
                    ?>

                </div>
            </div>
        </article>
    <?php endforeach; ?>
</div>