<h1> les produits d'une catégorie</h1>

<?php

$data = $data['input'];
$token = $data[0];
$ProductsToDisplay = $data[1];
// var_dump($ProductsToDisplay[1]);

?>


<?php foreach ($ProductsToDisplay as $key => $valeur) : ?>


    <h1><?= htmlspecialchars($valeur["productName"]); ?></h1>
    <p><?= htmlspecialchars($valeur["description"]); ?></p>
    <img class=" vignette" src=' public/uploads/<?= htmlspecialchars($valeur['picture']); ?>' alt=" produit" onclick="toggleClass('<?= htmlspecialchars($valeur['picture']); ?>')" />


    <?php
    // affichage des items diponible avec les prix 

    $items = $valeur['items'];
    // verification de l'existance d'items actifs 
    if (!empty($items)) {
        // remplissage d'une liste déroulante avec chaque item 
        $id = "idFormItem" . $valeur['id_product'];
        echo " Conditionnement :";
        echo " <select class='selectItems' name='item' id='$id'>";
        foreach ($items as $key => $item) {
            if ($valeur['id_product'] == $item['id_product']) : ?>
                <option value="<?= htmlspecialchars($item["id_item"]); ?>"><?= htmlspecialchars($item["pack"]); ?></option>
    <?php endif;
        }
        echo "</select>";
        $idPrix = "idPrix" . $valeur['id_product'];
        echo"<div id='$idPrix'>ici le prix </div>";
    }
    ?>


<?php endforeach; ?>