<a href="index.php?view=homePage">Home </a>
<a href="index.php?route=user&action=displayFormRegister">register </a>
<a href="index.php?route=items&action=test"> *** Test ***</a>
<a href="index.php?route=products&action=displayFormProducts"> === Gestion des produits </a>
<a href="index.php?route=products&action=displayFormAddProducts"> === Ajout produit</a>
<script src="public/js/main.js"></script>