<h1>Se connecter !</h1>


<?php require_once('errors.inc.phtml'); ?>

<form action="index.php?route=user&action=checkAndConnect" method="POST">
    <legend>Connexion</legend>

    <label for="email">Entrez votre email</label>
    <input type="text" name="email" size="30" value="<?php echo (isset($authUser['email'])) ?  $authUser['email'] : ""; ?>">


    <label for="email">Entrez votre mot de passe</label>
    <div>
        <input type="password" name="password" size="30" id="password_1">
        <button id="eyes1">
            <i id="eyesImag1" class="fas fa-eye-slash"></i>
        </button>
    </div>

    <!-- ajout du token -->
    <input id="token" name="token" type="hidden" value="<?= $data ?>">



    <input type="submit" value="Valider" />
</form>