<h1>Création d'un compte !</h1>

<?php require_once('errors.inc.phtml'); ?>
<!-- ?php require_once('_valids.phtml'); ?-->

<form class="tablo" enctype="multipart/form-data" action="?route=user&action=register" method="POST">

    <fieldset>
        <legend>Merci de renseigner les information suivantes :</legend>

        <input id="token" name="token" type="hidden" value="<?= $data ?>">

        <label for="firtName">Entrez votre nom</label>
        <input type="text" name="firstName" size="30" value="<?php echo (isset($addUser['addNom'])) ? $addUser['addNom'] : ""; ?>"><br>

        <label for="lastName">Entrez votre prénom</label>
        <input type="text" name="lastName" size="30" value="<?php echo (isset($addUser['addPrenom'])) ? $addUser['addPrenom'] : ""; ?>"><br>

        <span>Renseignez votre sexe : </span>
        <label for="sex">Feminin</label>
        <input type="radio" name="sex" id="female" value="f">
        <label for="sex">Masculin</label>
        <input type="radio" name="sex" id="male" value="m"><br>

        <label for="email">Entrez votre email</label>
        <input type="text" name="email" size="30" value="<?php echo (isset($addUser['addEmail'])) ? $addUser['addEmail'] : ""; ?>"><br>

        <label for="password">Choisissez un mot de passe</label>
        <input type="password" name="password" id="password_1" size="30"><br>

        <label for="password_verify">Confirmez le mot de passe choisi</label>
        <input type="password" name="password_confirme" id="password_2" size="30"><br>

        <input type="submit" value="Valider" /> <br>


    </fieldset>
</form>