<div class="headerHaut">
    <div class="logoEtTitre">
        <!-- le logo -->
        <a href="#" class="logo">Logo</a>
    </div>
</div>

<nav class="navbar">

    <!-- le bouton burger  -->
    <label for="btn" class="icon">
        <svg viewBox="0 0 80 80" width="40" height="40">
            <rect width="80" height="10"></rect>
            <rect y="30" width="80" height="10"></rect>
            <rect y="60" width="80" height="10"></rect>
        </svg>
    </label>
    <!-- input a faire disparaitre par un hidden -->
    <input type="checkbox" id="btn">
    <!-- la liste de boutons de nav  -->


    <ul class="nav-menu">
        <li class="nav-item">
            <a href="?view=homePage">Home</a>

            <!--  **************   Liste dynamique des listes disponibles ******************************************************  -->

        <li class="nav-item"><a class="pos" href=#>Nos produits + </a>
            <ul class="dropdownOnHover">
                <?php foreach ($data['categories'] as $key => $valeur) : ?>
                    <li class="drop-item"><a href="index.php?route=products&action=displayProductsOfOneCategory&cat=<?= htmlspecialchars($valeur["id_category"]); ?>"> <?= htmlspecialchars($valeur["categoryName"]); ?> </a>
                        <td></td>
                    </li>
                <?php endforeach; ?>
            </ul>
        </li>

        <!-- *********************************************************************************************** -->
        </li>
        <?php if (isset((($_SESSION['user'])['role'])) && (!empty($_SESSION['user'])) && (($_SESSION['user'])['role']) === 'admin') : ?>
            <li class="nav-item"><a class="pos" href=#>Administration + </a>
                <ul class="dropdownOnHover">
                    <li class="drop-item"><a href="index.php?route=products&action=displayFormProducts"> Gestion des produits </a></li>
                    <li class="drop-item"><a href="index.php?route=products&action=displayFormAddProducts">Ajout produit</a></li>
                    <li class="drop-item"><a href="index.php?route=carouselsPics&action=displayFormAddPic">Ajout image carrousel</a></li>
                </ul>
            </li>
        <?php endif ?>



        <?php if (isset((($_SESSION['user'])['firstName'])) && (!empty($_SESSION['user']))) : ?>
            <li class="nav-item"><a href="?route=User&action=logoutUser">LogOut</a></li>
        <?php else : ?>
            <li class="nav-item"><a href="?route=user&action=displayFormRegister">register </a></li>
            <li class="nav-item"><a href="?route=user&action=displayFormConnect"> login </a></li>
        <?php endif ?>


        <li class="nav-item">
            <label for="btn2" class="show">Mon compte +</label>
            <input type="checkbox" id="btn2">
            <ul class="dropdown">
                <li class="drop-item">
                    <a href="#">Mon Profil</a>
                </li>
                <li class="drop-item">
                    <a href="#">Articles</a>
                </li>
            </ul>
        </li>

    </ul>
</nav>