

<div class="my-flipster">
    <ul>
        <li>
            <img src="public/uploads/slider/63bd118a5534b-DSC_0383JPG.jpg" alt="promo noel">
        </li>
        <li>
            <img src="public/uploads/slider/63bd111f7d01e-DSC_0352JPG.jpg" alt="promo noel">
        </li>
        <li>
            <img src="public/uploads/slider/63bd113e68e81-DSC_0353JPG.jpg" alt="promo noel">
        </li>
        <li>
            <img src="public/uploads/slider/63bd11568dfd0-DSC_0367JPG.jpg" alt="promo noel">
        </li>
        <li>
            <img src="public/uploads/slider/63bd11051aa24-DSC_0350JPG.jpg" alt="promo noel">
        </li>
        <li>
            <img src="public/uploads/slider/63bd157e5670b-DSC_0394JPG.jpg" alt="promo noel">
        </li>
    </ul>
</div>