<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>


    <link rel="stylesheet" href="public/styles/css/jquery.flipster.css">
    <link rel="stylesheet" href="public/styles/css/style.css">
</head>

<body>

    <header>
        <?php require "public/views/header.inc.phtml" ?>
    </header>

    <?php if (isset($_SESSION['message'])) : ?>
        <?= $_SESSION['message']; ?>
        <?php unset($_SESSION['message']) ?>
    <?php endif; ?>

    <main>
        <?php require "public/views/$view.phtml" ?>
    </main>

    <footer>
        <?php require "public/views/footer.inc.phtml" ?>
    </footer>



  

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js" integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ==" crossorigin="anonymous" eferrerpolicy="no-referrer"></script>

     <script src="public/js/jquery.flipster.min.js"></script>

    <script src="public/js/main.js"></script>

</body>





</html>