<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="public/styles/css/style.css">
</head>

<body>

    <header>
        <?php require "public/views/header.inc.phtml" ?>
    </header>

    <?php if (isset($_SESSION['message'])) : ?>
        <?= $_SESSION['message']; ?>
        <?php unset($_SESSION['message']) ?>
    <?php endif; ?>

    <main>
        <?php require "public/views/$view.phtml" ?>
    </main>

    <footer>
        <?php require "public/views/footer.inc.phtml" ?>
    </footer>

</body>





</html>