<?php if (isset((($_SESSION['user'])['role'])) && (!empty($_SESSION['user'])) && (($_SESSION['user'])['role']) === 'admin') : ?>

    <h1> Formulaire Carrousel </h1>

    <?php require_once('public/views/errors.inc.phtml'); ?>

    <!-- Affichage de l'image si modification -->
    <?php if (isset($data['input']['pic'])) : ?>
        <img class=" vignette" src=' public/uploads/<?= htmlspecialchars($data['input']['pic']['picture']); ?>' alt="image" onclick="toggleClass('<?= htmlspecialchars($data['input']['pic']['picture']); ?>')" />
        <div id="<?= htmlspecialchars($data['input']['pic']['picture']); ?>" class="modal-window">
            <img src=' public/uploads/<?= htmlspecialchars($data['input']['pic']['picture']); ?>' alt="image" onclick="toggleClass('<?= htmlspecialchars($data['input']['pic']['picture']); ?>')" />
        </div>
    <?php endif; ?>


    <form method="post" enctype="multipart/form-data" action=" ?route=carouselsPics&action=AddOrModifyCarouselPic">

        <input id="token" name="token" type="hidden" value="<?= $data['input']['token'] ?>">

        <label for="description">Description</label>
        <input type="text" name="description" id="description" placeholder=" description " value="<?php echo (isset($data['input']['pic']['description'])) ? htmlspecialchars($data['input']['pic']['description']) : ""; ?>">
        <br>

        <label for="picture">Photo</label>
        <input type="file" id="uploadImage" name="picture" ><br>

        <?php if (isset($data['input']['pic'])) : ?>
            <!-- on recupère l'id de la photo si modif -->
            <input id="id" name="id" type="hidden" value="<?= htmlspecialchars($data['input']['pic']["id_carousel"]); ?>">
            <!-- Pour pouvoir recuperer l'ancienne photo si pas de changement -->
            <input type="hidden" id="photo_recup" name="photo_recup" value="<?= htmlspecialchars($data['input']['pic']['picture']); ?>">
        <?php endif; ?>

        <fieldset>
            <legend>Produit actif? </legend>
            <label class="radio" for=" actif">Actif</label>
            <input type="radio" id="actif" name="status" value="actif" checked>
            <label class="radio" for="actif">Inactif</label>
            <input type="radio" id="inactif" name="status" value="inactif" <?php if ((isset($data['input']['pic'])) && ($data['input']['pic']['status']) === ("inactif")) echo "checked"; ?>>
        </fieldset>

        <div class="preview">
            <img id="uploadPreview">
        </div>

        <input type="submit" value="enregistrement">

    </form>

<?php else : ?>
    <h2> Affichage non autorisé </h2>
<?php endif; ?>