<?php if (isset((($_SESSION['user'])['role'])) && (!empty($_SESSION['user'])) && (($_SESSION['user'])['role']) === 'admin') : ?>
    
<?php require_once('public/views/errors.inc.phtml'); ?>
<h1> Formulaire de création d'items </h1>


<?php var_dump($data); ?>;

<?php
if (isset($data['input'][3]) && (!empty($data['input'][3]))) {
    $item = $data['input'][3];
};
?>




    <div>
        <h2>Vous voulez créer un item pour le produit <?= htmlspecialchars($data['input'][2]["productName"]); ?></h2>
    </div>

    <img class=" vignette" src=' public/uploads/<?= htmlspecialchars($data['input'][2]['picture']); ?>' alt=" produit" onclick="toggleClass('<?= htmlspecialchars($data['input'][2]['picture']); ?>')" />
    <div id="<?= htmlspecialchars($data['input'][2]['picture']); ?>" class="modal-window">
        <img src=' public/uploads/<?= htmlspecialchars($data['input'][2]['picture']); ?>' alt="produit" onclick="toggleClass('<?= htmlspecialchars($data['input'][2]['picture']); ?>')" />
    </div>


    <form class="tablo" action="?route=items&action=createItemProcess" method="POST">

        <input id="token" name="token" type="hidden" value="<?= $data['input'][0]?>">
        <input id="idProduct" name="idProduct" type="hidden" value="<?= htmlspecialchars($data['input'][2]['id_product']) ?>">


        <?php if (isset($item['itemRef'])) : ?>
            <input id="id" name="id" type="hidden" value="<?= htmlspecialchars($item["id_item"]); ?>">
        <?php endif; ?>




        <fieldset>

            <legend>Merci de renseigner les information suivantes :</legend>
           
            <label for="vatRef">Entrez la référence </label>

            <input type="text" name="ref" size="30" minlength="2" maxlength="30" pattern="^[a-zA-Z0-9 '-]+$" required value="<?php echo (isset($item['itemRef'])) ? htmlspecialchars($item['itemRef']) : ""; ?>"><br>

            <label for="pack">Entrez le conditionnement</label>
            <input type="text" name="pack" size="30" minlength="2" maxlength="30" pattern="^[a-zA-Z0-9 '-]+$" required value="<?php echo (isset($item['pack'])) ? htmlspecialchars($item['pack']) : ""; ?>"><br>

            <label for="price">Entrez le prix unitaire</label>
            <input type="text" name="price" size="30" required value="<?php echo (isset($item['price'])) ? htmlspecialchars($item['price']) : ""; ?>"><br>

            <label for="stock">Entrez le stock</label>
            <input type="number" name="stock" size="30" required value="<?php echo (isset($item['stock'])) ? htmlspecialchars($item['stock']) : ""; ?>"><br>

            <label for="vat">Tva applicable </label>
            <select name="vat" id="vat">
                <?php foreach ($data['input'][1] as $key => $valeur) : ?>
                    <option value="<?= ($valeur["id_vat"]); ?>" <?php if ((isset($item['itemRef'])) && (($item["id_vat"]) === ($valeur["id_vat"]))) echo "selected"; ?>><?= htmlspecialchars($valeur["name"]); ?>
                    </option>
                <?php endforeach; ?>
            </select><br>
        </fieldset>
        <fieldset>
            <legend>Produit actif? </legend>
            <label class="radio" for=" actif">Actif</label>
            <input type="radio" id="actif" name="status" value="actif" checked>
            <label class="radio" for="actif">Inactif</label>
            <input type="radio" id="inactif" name="status" value="inactif" <?php if ((isset($item['itemRef'])) && ($item["status"]) === ("inactif")) echo "checked"; ?>>
        </fieldset>

        <input type="submit" value="Valider" /> <br>



    </form>

<?php else : ?>

    <h2> Affichage non autorisé </h2>

<?php endif; ?>