<!-- $token = $data['input'][0]; -->
<?php if (isset((($_SESSION['user'])['role'])) && (!empty($_SESSION['user'])) && (($_SESSION['user'])['role']) === 'admin') : ?>

    <h1> visualisation des produits</h1>

    <table class='catalog'>
        <thead>
            <tr>
                <th>Référence</th>
                <th>Categorie</th>
                <th>Nom</th>
                <th>Teaser</th>
                <th>Description</th>
                <th>Infos</th>
                <th></th>
                <th></th>
            </tr>
        </thead>


        <tbody>
            <?php foreach ($data['input'][1] as $key => $valeur) : ?>
                <tr>
                    <td><?= htmlspecialchars($valeur["productRef"]); ?> </td>
                    <td><?= htmlspecialchars($valeur["categoryName"]); ?></td>
                    <td><?= htmlspecialchars($valeur["productName"]); ?></td>
                    <td><?= htmlspecialchars($valeur["teaser"]); ?></td>
                    <td><?= htmlspecialchars($valeur["description"]); ?></td>
                    <td><?= htmlspecialchars($valeur["infos"]); ?></td>
                    <td><img class="vignette" src=' public/uploads/<?= htmlspecialchars($valeur['picture']); ?>' 
                            alt=" produit" 
                            onclick="toggleClass('<?= htmlspecialchars($valeur['picture']); ?>')" />
                    </td>
                    <div id="<?= htmlspecialchars($valeur['picture']); ?>" 
                        class="modal-window"><img src=' public/uploads/<?= htmlspecialchars($valeur['picture']); ?>' 
                        alt="produit" 
                        onclick="toggleClass('<?= htmlspecialchars($valeur['picture']); ?>')" />
                    </div>
                    <td>
                        <a class="bouton" href="?route=Items&action=displayItems&id=<?= htmlspecialchars($valeur['id_product']); ?>">Items</a>
                    </td>
                    <td>
                        <a class="bouton" href="?route=Products&action=editProduct&id=<?= htmlspecialchars($valeur['id_product']); ?>">Modifier</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

<?php else : ?>
    <h2> Affichage non autorisé </h2>
<?php endif; ?>