<h1> visualisation des produits</h1>


<?php

$token = $data[0];
$values = $data[1];

?>




<table class='catalog'>
    <thead>
        <tr>
            <th>Référence</th>
            <th>Categorie</th>
            <th>Nom</th>
            <th>Teaser</th>
            <th>Description</th>
            <th>Infos</th>
            <th></th>
            <th></th>

        </tr>
    </thead>


    <tbody>

        <?php foreach ($values as $key => $valeur) : ?>
            <tr>
                <td><?= htmlspecialchars($valeur["productRef"]); ?> </td>
                <td><?= htmlspecialchars($valeur["categoryName"]); ?></td>
                <td><?= htmlspecialchars($valeur["productName"]); ?></td>
                <td><?= htmlspecialchars($valeur["teaser"]); ?></td>
                <td><?= htmlspecialchars($valeur["description"]); ?></td>
                <td><?= htmlspecialchars($valeur["infos"]); ?></td>
                <td><img class=" vignette" src=' public/uploads/<?= htmlspecialchars($valeur['picture']); ?>' alt=" produit" onclick="toggleClass('<?= htmlspecialchars($valeur['picture']); ?>')" />
                </td>
                <div id="<?= htmlspecialchars($valeur['picture']); ?>" class="modal-window">
                    <img src=' public/uploads/<?= htmlspecialchars($valeur['picture']); ?>' alt="produit" onclick="toggleClass('<?= htmlspecialchars($valeur['picture']); ?>')" />
                <div>
                <td>
                    <a href="?route=Items&action=displayItems&id=<?= $valeur['id_product']; ?>">Items</a>
                </td>
                <td>
                    <a href="?route=Products&action=editProduct&id=<?= $valeur['id_product']; ?>">Modifier</a>
                </td>

            </tr>
        <?php endforeach; ?>
    </tbody>
</table>