
<h1> Formulaire Produits </h1>


<?php
$data = $data['input'];
$token = $data[0];
$values = $data[1]; // recup des catégories disponibles 
?>
<?php require_once('public/views/errors.inc.phtml'); ?>


<!-- <form method="post" enctype="multipart/form-data" action=" ?route=Products&action=addProduct" enctype="multipart/form-data"> -->
<form method="post" enctype="multipart/form-data" action=" ?route=Products&action=AddOrModifyProductProcess" enctype="multipart/form-data">

    <fieldset>
        <input id="token" name="token" type="hidden" value="<?= $token ?>">

        <label for="categorie">Categorie</label>

        <select name="category" id="category">
            <?php foreach ($values as $key => $valeur) : ?>
                <option value="<?= htmlspecialchars($valeur["id_category"]); ?>"><?= htmlspecialchars($valeur["categoryName"]); ?></option>
            <?php endforeach; ?>
        </select><br>

        <label for="productName">Nom du produit</label>
        <input type="text" id="productName" name="productName" placeholder="le nom du produit"> <br>

        <label for=" reference">Reférence</label>
        <input type="text" id="reference" name="reference" placeholder="la référence de produit"> <br>

        <label for="teaser">Description courte</label>
        <input type="text" id="teaser" name="teaser" placeholder="description courte"> <br><br>

        <label for="description">Iescription</label>
        <textarea name="description" id="description" placeholder="la description du produit"></textarea><br>

        <label for="infos">Infos</label>
        <input type="text" id="infos" name="infos" placeholder="infos"> <br>

        <label for="picture">Photo</label>
        <input type="file" id="uploadImage" name="picture" onchange="PreviewImage(event)"><br>


        <fieldset>
            <legend>Produit actif? </legend>
            <label class="radio" for=" actif">Actif</label>
            <input type="radio" id="actif" name="status" value="actif" checked>
            <label class="radio" for="actif">Inactif</label>
            <input type="radio" id="inactif" name="status" value="inactif">
        </fieldset>

        <div class="preview">
            <img id="uploadPreview">
        </div>

        <input type="submit" value="enregistrement">




</form>